version: '3'

services:
 app:
  build:
   context: .
  ports:
   - 5000:5000
  links:
   - db
  volumes:
   - ./app:/app
  
 db:
  image: mysql:5.7
  restart: unless-stopped
  tty: true
  ports:
     - "3306:3306"
  environment:
     MYSQL_DATABASE: flask
     MYSQL_ROOT_PASSWORD: secret
     MYSQL_HOST: '0.0.0.0'
     MYSQL_USER: root
     MYSQL_PASSWORD: secret
    
  volumes:
      - mysql_storage_new:/var/lib/mysql
volumes:
    mysql_storage_new:
